name: Conventional PR Title
author: step-security
description: Ensure your PR title matches the Conventional Commits spec (https://www.conventionalcommits.org/).
inputs:
  success-state:
    description: Description of the status check if validation succeeds.
    required: false
    default: Title follows the specification.
  failure-state:
    description: Description of the status check if validation fails.
    required: false
    default: Title does not follow the specification.
  context-name:
    description: Persistent status check context key
    required: false
    default: conventional-pr-title
  preset:
    description: Conventional changelog preset to use.
    required: false
    default: conventional-changelog-conventionalcommits@7
  target-url:
    description: URL to be used when linking the "Details" in the actions overview.
    required: false
    default: https://www.conventionalcommits.org/en/v1.0.0/#summary
runs:
  using: "docker"
  image: "docker://ghcr.io/step-security/conventional-pr-title-action:v3.2.5@sha256:13c538cde9f8f731b142fce7038f6927a8bf18975a958268087a9c372a0a22ed" #v3.2.5

branding:
  icon: shield
  color: green
